In [1]:
import numpy as np

## Latihan 4

1. membuat vektor nol / 1D dengan size 10 dan update nilai ke 5 dengan 11

In [2]:
zeros_matrix = np.zeros(10)
zeros_matrix

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#mengupdate nilai ke 5 dalam matriks dengan 11
zeros_matrix[5] = 11
zeros_matrix

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

penjelasan : dibuat vektor nol dengan banyak elemen 10 dan mengupdate nilai ke 5 dengan 11, disini saya memanfaatkan index untuk mengupdate atau mengganti nilai ke 5 menjadi 11

2. Tulis sebuah program numpy untuk menciptakan sebuah array berukuran 2x3 dan ubah menjadi array 3x2

In [4]:
arr = np.array([[1,2,3],
               [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#cek shape
arr.shape

(2, 3)

In [6]:
#mengubah menjadi array 3x2
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
arr.shape

(2, 3)

penjelasan : dibuat matriks berukuran 2x3 yang kemudian akan diubah menjadi matriks berukuran 3x2, disini saya menggunakan fungsi .T untuk mentranspose kan matriks 2x3 tersebut

3. Tulis sebuah program numpy untuk membuat sebuah array 2d dengan angka 1 sekelilingnya dan angka 0 didalam 

In [8]:
#membuat matriks awal
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#memberi angka 0 didalam
a[1:-1,1:-1] = 0
a

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

penjelasan : disini saya membuat matriks 3x3 sebagai matrik awal, lalu mengubah elemen tengahnya menjadi 0 dengan menggunakan index sehingga menjadi matriks yang diinginkan 

4. Perhatikan matriks berikut ini. Akses [2,1,1]

In [10]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

In [11]:
#mengakses [2,1,1]
z[2,1,1]

2

penjelasan : mengakses [2,1,1] berarti kita mengambil array dengan index ke 2 baris ke 1 dan kolom 1 oleh karena itu untuk [2,1,1] adalah 2

# ASSIGNMENT

1. Membuat sebuah matriks berukuran 4x4 dengan nilai dari 0 sampai 3

In [12]:
from numpy import random

In [13]:
x = random.randint(0,3,size=(4,4))
x

array([[2, 2, 1, 2],
       [1, 1, 2, 0],
       [1, 2, 2, 1],
       [2, 1, 2, 2]])

penjelasan : dengan menggunakan random yang ada di numpy dan memanfaatkan fungsi randint saya bisa membuat matriks 4x4 dengan elemen elemennya nilainya dari 0 sampai 3

2. membuat sebuah array dengan ukuran 4x4 dan ubah menjadi 2 array

In [14]:
#membuat matriks awal
a1 = random.randint(0,16,size=(4,4))
a1

array([[ 5, 12,  7,  7],
       [ 8,  7,  5, 10],
       [ 9, 15,  4, 11],
       [ 9, 14, 15,  9]])

In [17]:
#memisahkan menjadi 2 array
a2 = np.hsplit(a1,(2,6))
a2

[array([[ 5, 12],
        [ 8,  7],
        [ 9, 15],
        [ 9, 14]]),
 array([[ 7,  7],
        [ 5, 10],
        [ 4, 11],
        [15,  9]]),
 array([], shape=(4, 0), dtype=int32)]

penjelasan : disini saya membuat matriks berukuran 4x4 terlebih dahulu , dan dengan memanfaatkan fungsi hsplit maka saya bisa membuat matriks yang telah saya buat menjadi 2 array 